version: "3"
services:
  mongo:
    image: mongo:3.5.13
    restart: always
    expose:
      - "27017"

  rabbitmq:
    image: rabbitmq:3.6.12
    restart: always
    expose:
      - "5672"

  worker:
    build: .
    command: celery -A whistleblower.tasks worker -B
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - .env
    environment:
      - CLOUDAMQP_URL=pyamqp://guest:guest@rabbitmq:5672//
      - MONGO_DATABASE=whistleblower
      - MONGO_URL=mongodb://mongo:27017/
    volumes:
      - ./data:/usr/src/app/data
      - ./rosie:/usr/src/app/rosie
      - ./tests:/usr/src/app/tests
      - ./whistleblower:/usr/src/app/whistleblower
