version: "3"
services:
  mongo:
    image: mongo:3.5.13
    restart: always
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.6.12
    restart: always
    ports:
      - 5672:5672

  worker:
    build: .
    command: celery -A whistleblower.tasks worker -B
    restart: always
    depends_on:
      - mongo
      - rabbitmq
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
      - ./rosie:/usr/src/app/rosie
      - ./tests:/usr/src/app/tests
      - ./whistleblower:/usr/src/app/whistleblower
